### PR TITLE
Quick and dirty support for coverage

### PR DESCRIPTION
**Pull request by couto**
A really quick and dirty way of supporting code coverage tests.

```
cafemocha: {
    unit: {
        src: '<%= files.test %>',
        options: {
            ui: 'exports',
            reporter: 'nyan'
        }
    },
    coverage: {
        files: { 'coverage/index.html': '<%= cafemocha.unit.src %>'},
        options: {
            ui: 'exports',
            reporter: 'html-cov',
            env: 'JOHNNIE_COVERAGE'
        }
    }
}
```

it does by intercepting mocha's `stdout` and writing the info in the destination file, it also supports an environmental variable so that is possible to load the previously converted files for coverage analysis, just like specified [here](http://tjholowaychuk.com/post/18175682663/mocha-test-coverage)

_Note_: this doesn't run the [jscoverage](https://github.com/visionmedia/node-jscoverage) binary, I've chosen to do it with a separated task, since I believe that it distances itself from this tasks context.

Also this was really quick and dirty, you might want to do some tests first :worried:

### CODE REVIEW

**Comment by jdavis** [comment]
Hey @Couto, I'm going to be really busy in the next few weeks. My university finals are just around the corner. I'll get to this as soon as I can after May 10th when I get out for the summer =]

In the meantime... I do think this would be a nice feature. I just don't fully understand test coverages (sorry for my ignorance). Could you give an example of where it's used and what it accomplishes? Then how does this pull request fit into that?

**Comment by couto** [comment]
A pretty quick and ultra minimalistic example of code coverage:

Screen Shot 2013-04-29 at 08 58 54

Ok... Let's see if I can explain correctly =) (english is not my first language so this can turn a little tricky for me)
Code coverage is a way of registering which lines of code have been tested/called, It's pretty useful to find dead code and/or checking what hasn't been tested yet (it really depends on the way you use)

In the picture above, it clearly states that the `untested` function was never called, this example can be found [here](https://github.com/Couto/johnnie) at this point the master branch is just a bare bones project so it's as minimalistic as possible, and it's also using this pull request, on the other hand [mocha](https://github.com/visionmedia/mocha) itself is a nice example of a more realistic, in use, code coverage, just clone it, install dependencies and run `make lib-cov && make test-cov && open coverage.html`

I really don't know If I explained myself correctly, but feel free to comment or ask questions.

**Comment by xzyfer** [comment]
Any progress on this?

**Comment by jdavis** [comment]
Hey @xzyfer and @Couto, I am finally done with school and moved into my new place. I will find time over the next few days to work on this. Thanks for being patient, guys!

**Comment by AndrewKeig** [comment]
hey jd; any movement on this; would really appreciate this feature; none of the other grunt tasks I have tried seem to implement this feature.  Thanks..

**Comment by jdavis** [comment]
Hey @AndrewKeig, @Couto, @xzyfer, I'm taking a look at it all today :). Thanks for being patient, guys!

**Comment by couto** [comment]
@jdavis Don't forget to take a look in this [Gruntfile](https://github.com/Couto/johnnie/blob/dev/Gruntfile.js#L100-L117) It might help.

If you need any help, feel free to ask :)

**Comment by jdavis** [comment]
@Couto You must have read my mind because I was on that exact part, haha.

**Comment by jdavis** [comment]
Alright guys, I think I have something working.

I have it saved in the [coverage](https://github.com/jdavis/grunt-cafe-mocha/tree/coverage) branch. I took a lot of the ideas that @Couto (which I saw he got a bit from [here](https://github.com/visionmedia/express) :smile:) used and implemented them in the new branch.

The example in the [example/](https://github.com/jdavis/grunt-cafe-mocha/tree/coverage/example) directory uses the new feature.

Also the [README](https://github.com/jdavis/grunt-cafe-mocha/blob/coverage/README.md) has been updated to reflect the new options.

Like @Couto said, the actual coverage instrumentation doesn't belong in grunt-cafe-mocha itself so I left that out.

Let me know what you guys (@Couto, @xzyfer and @AndrewKeig) think!

**Comment by AndrewKeig** [comment]
Thanks Josh; works great..

Only issue I could find was setting env; from your example I thought I could change this; but maybe im missing something..

I already have a grunt task for jscoverage: grunt-jscoverage; so feel free to use that; simplifies the grunt file to the following:

```
grunt.initConfig({
    cafemocha: {
      test: {
          src: 'test/*.js',
          options: {
              ui: 'bdd',
              reporter: 'spec',
          },
      },
      coverage: {
         src: 'test/*.js',
          options: {
            ui: 'bdd',
            reporter: 'html-cov',
            coverage: {
                output: 'coverage.html'
            }
          }
      },
    },
    jscoverage: {
      options: {
        inputDirectory: 'lib',
        outputDirectory: 'lib-cov'
      }
    }
  });
  grunt.registerTask('test', [ 'cafemocha:test' ]);
  grunt.registerTask('coverage', [ "jscoverage", "cafemocha:coverage" ]);
```

**Comment by jdavis** [comment]
Hey @AndrewKeig you're right, you can change it. Currently the behavior is to set the ENV variable to whatever the `coverage.env` value is set to.

So for example if `coverage.env = 'TESTS'` then `process.env['COV'] = 'TESTS'`.

Would it make more sense to do this instead? If `coverage.env = 'TESTS'` then `process.env['TESTS'] = 1`

When I first saw @Couto's example, I didn't know which one to implement so I'm totally open to changing it.

**Comment by couto** [comment]
Honestly both ways are fine by me as long as you document them... =)
Most people are used to follow the "standard" set by projects like Express and Mocha... but there's nothing written saying that people have to use `process.env['whatever']` or `process.env.COV = 'something'`

It's all a matter of personal preference honestly... At least I see no disadvantages using any of those two ways...

**Comment by jdavis** [comment]
What is the "standard" that Express/Mocha set? Is it `process.env['whatever']` or `process.env.COV`?

**Comment by couto** [comment]
oh lol! 

I just went and check... 
[Express](https://github.com/visionmedia/express/blob/master/index.js) they use `process.env['EXPRESS_COV']`
[Mocha](https://github.com/visionmedia/mocha/blob/master/index.js) they use `process.env['COV']`

the "standard" is a just a variable name of your chose with a "truthy" value (although it might look confusing because in Mocha the variable is called 'COV')

**Comment by jdavis** [comment]
K cool. Let's go with the quasi-standard! I'll update the docs and link the commit here.

**Comment by jdavis** [comment]
Okay, I added the documentation and updated how the `coverage.env` variable is used.

How does this look https://github.com/jdavis/grunt-cafe-mocha/commit/141f2504b196e0d50cb87992ac314f7175f2a1f8?

**Comment by AndrewKeig** [comment]
Looks good..

**Comment by jdavis** [comment]
Alright guys, I just bumped the version to `0.1.4` and published it to [NPM](https://npmjs.org/package/grunt-cafe-mocha) so feel free to use the new one!

Feel free to make a new issue if you have any more problems!

**Comment by xzyfer** [comment]
This all happened over night here, but judging by the discussion it seems like a decent job. I'll see how it goes when I start using it :)

**Comment by jdavis** [comment]
Haha, hopefully it went well. Just let me know though if you experience any issues, @xzyfer.

**Pull request closed without merging**
